from manim import * 
import numpy as np 

    
class OpeningManim(Scene): 
    def construct(self): 
        # self.camera.background_color = WHITE
        title_1 = Tex(r"Binômio").scale(5) 
        title_2 = Tex(r"de").scale(5) 
        title_3 = Tex(r"Newton").scale(5) 
        eq_a = MathTex(r"(a+b)^n=\sum_{k=0}^n").scale(1.7) 
        eq_b = MathTex(r"\binom{n}{k}").scale(1.7) 
        eq_c = MathTex(r"a^{n-k}b^k").scale(1.7) 
        eq_d = MathTex(r"=\frac{n!}{k!(n-k)!").scale(1.7) 
        title_1.shift(UP*8) 
        title_2.next_to(title_1, DOWN, buff=0.5) 
        title_3.next_to(title_2, DOWN, buff=0.5) 
        eq_a.next_to(title_3, DOWN, buff=2.5).shift(LEFT*2) 
        eq_b.next_to(eq_a) 
        eq_c.next_to(eq_b) 
        tit=VGroup(title_1,title_2,title_3) 
        rectangle = Rectangle(width=1.8, height=1, stroke_width=1) 
        rectangle.set_x(0.7) 
        rectangle.set_y(0.1) 
        eq = VGroup(eq_a, eq_b, eq_c) 
        self.play( Write(title_1), Write(title_2), Write(title_3), run_time=4) 
        self.play(Write(eq), run_time=4) 
        eq2 = eq_b.copy() # Cria uma cópia da equação eq 
        self.play(FadeOut(tit), (eq2.animate.shift((-4,4,0)), (eq.animate.shift(UP * 8)))) 
        eq_d.next_to(eq2) 
        self.play(Write(eq_d), run_time=4) 
        ex = Text(r"Exemplo") 
        ex.set_x(0) 
        ex.set_y(1) 
        eq_ex = MathTex(r"(a+b)^3=\binom{3}{0}a^{3}b^0+\binom{3}{1}a^{2}b^1+\binom{3}{2}a^{1}b^2+\binom{3}{3}a^{0}b^3").scale(1) 
        eq_ex2 = MathTex(r"(a+b)^3=\binom{3}{0}a^{3}+\binom{3}{1}a^{2}b+\binom{3}{2}ab^2+\binom{3}{3}b^3").scale(1.1) 
        eq_ex3 = MathTex(r"(a+b)^3=1a^{3}+3a^{2}b+3ab^2+1b^3").scale(1.3) 
        eq_ex4 = MathTex(r"(a+b)^3=a^{3}+3a^{2}b+3ab^2+b^3").scale(1.5) 
        eq_ex.next_to(ex, DOWN) 
        eq_ex2.next_to(ex, DOWN) 
        eq_ex3.next_to(ex, DOWN) 
        eq_ex4.next_to(ex, DOWN) 
        self.play(Write(eq_ex), run_time=4) 
        self.play(TransformMatchingShapes(eq_ex,eq_ex2)) 
        self.play(ReplacementTransform(eq_ex2,eq_ex3), run_time=2) 
        self.play(ReplacementTransform(eq_ex3,eq_ex4), run_time=2) 
        eq_f = MathTex(r"T_{k+1}=\binom{n}{k}a^{n-k}b^k").scale(1.7) 
        eq_f1 = MathTex(r"T_{2}=\binom{3}{1}a^2b").scale(1.7) 
        eq_f2 = MathTex(r"T_{2}=3a^2b").scale(1.7) 
        eq_f.next_to(eq_ex4, DOWN*4) 
        eq_f1.next_to(eq_f, DOWN, buff=1.5) 
        eq_f2.next_to(eq_f, DOWN, buff=1.5) 
        self.play(Create(rectangle)) 
        self.play(rectangle.animate.move_to((-2.7,-2.4,0))) 
        self.play(Write(eq_f), run_time=4) 
        self.play(FadeOut(rectangle),Write(eq_f1)) 
        self.play(ReplacementTransform(eq_f1, eq_f2)) 
        self.wait(5)